### PR TITLE
added-wireframe

### PR DESCRIPTION
**Pull request by daprieu**
added wireframe to the code!

### CODE REVIEW

**Review by kylieanyce — APPROVED** [review]
looks good!

**Comment by samj0516** [comment]
Finally checked it out and it looks good! Go ahead and merge

**Review by samj0516 — APPROVED** [review]
Fetched and previewed. Looked good.

**Review by Thomas88s — COMMENTED** [review]
Looks good!

**Review by Thomas88s — APPROVED** [review]
Looks good!

**Pull request merged**
