### PR TITLE
added new blank files to get started

### PR DESCRIPTION
**Pull request by samj0516**
Please make sure you can see everything!

### CODE REVIEW

**Review by daprieu — APPROVED** [review]
Looks good!!!

**Review by kylieanyce — APPROVED** [review]
Looks good!

**Review by Thomas88s — COMMENTED** [review]
Everything looks good!

**Review by Thomas88s — APPROVED** [review]

**Review by Thomas88s — APPROVED** [review]
Great job again!

**Comment by samj0516** [comment]
Merged alex's branch. Pleaser re-review

**Review by daprieu — APPROVED** [review]

**Review by kylieanyce — APPROVED** [review]
it works!

**Pull request merged**
