### PR TITLE
started layout of czech page

### PR DESCRIPTION
**Pull request by daprieu**
added layout of czech page

make sure that you are able to see iceland and czech page code

### CODE REVIEW

**Review by Thomas88s — APPROVED** [review]
Cool!

**Review by samj0516 — CHANGES_REQUESTED** [review]
Looks good! Just change the countryList to your country

**Review by kylieanyce — CHANGES_REQUESTED** [review]
needs changes to class names

**Comment by daprieu** [comment]
made changes to be reviewed!

**Comment by daprieu** [comment]
...
git fetch --all
git checkout ap-czechRepublicPage
...

**Review by samj0516 — APPROVED** [review]

**Review by kylieanyce — APPROVED** [review]

**Pull request merged**
