### PR TITLE
created dirs and sub dirs for morocco, moved CSS for morocco to styles

### PR DESCRIPTION
**Pull request by kylieanyce**
created directories and sub directories for morocco cities, landmarks, and celebs. 
also moved morocco CSS file from countries folder to styles folder.
``````````
git fetch --all
git checkout kb-createJSdirs-subDirs-morocco
serve
`````````
please make sure you see the dirs and sub dirs under morocco in js and that the morocco CSS file is in the correct location under styles.

### CODE REVIEW

**Review by Thomas88s — APPROVED** [review]

**Review by samj0516 — APPROVED** [review]
git it girl!

**Comment by Thomas88s** [comment]
revamped review

**Review by Thomas88s — APPROVED** [review]
revamped review

**Review by daprieu — APPROVED** [review]
looking good!!! can see new code. 
Not sure it really matters but I went back and capitalized the first letter of all my js files

**Pull request merged**
