### PR TITLE
added index framework

### PR DESCRIPTION
**Pull request by samj0516**
Make sure you can see the index html framework

### CODE REVIEW

**Review by Thomas88s — APPROVED** [review]
Perfect!

**Review by daprieu — APPROVED** [review]

**Review by kylieanyce — CHANGES_REQUESTED** [review]
please add links for the images :)

**Review by daprieu — CHANGES_REQUESTED** [review]
link us up! haha

**Review by daprieu — APPROVED** [review]

**Review by Thomas88s — APPROVED** [review]
Perfect!

**Review by kylieanyce — APPROVED** [review]

**Pull request merged**
